### ISSUE TITLE
Repo server is down.

### ISSUE THREAD

**Issue by jaracil** [ArteMisc/libgodium#1]
go get go.artemisc.eu/godium

package go.artemisc.eu/godium: unrecognized import path "go.artemisc.eu/godium" (https fetch: Get https://go.artemisc.eu/godium?go-get=1: dial tcp 149.210.176.2:443: getsockopt: connection refused)

**Comment by ArteMisc** [comment]
Seems I have to fix my setup, thanks for letting me know!
