### ISSUE TITLE
NewBlake2bSaltPersonal always produces the same result

### ISSUE THREAD

**Issue by ORBAT** [ArteMisc/libgodium#2]
A `blake2b.Config` is created on line 91 and then initialized, but line 101 creates an empty `Config` that is then given to `blake2b.New`:

https://github.com/ArteMisc/libgodium/blob/977c77a70281fd6e021bc813249b5ce2d5daf70d/generichash/blake2b.go#L90-L107

this means that all keys derived with `NewBlake2bSaltPersonal` will be equal.

**Comment by ArteMisc** [comment]
Thanks for catching this!
