### ISSUE TITLE
KeyPairSeedEd25519 ignores seed

### ISSUE THREAD

**Issue by Hades32** [ArteMisc/libgodium#6]
See:
https://github.com/ArteMisc/libgodium/blob/master/sign/ed25519_sign.go#L56

This returns different values from what libsodium returns. From looking at the implementation it's probably because the seed parameter is being ignored completely.

**Comment by ArteMisc** [comment]
That is indeed a bug, thanks for the report.

Should be easy to fix, will make some time for that this week.
