### ISSUE TITLE
Stackoverflow in chacha20

### ISSUE THREAD

**Issue by challarao** [ArteMisc/libgodium#8]
> func (s *chacha20Impl) ReKey(key, nonce []byte) {
> 	s.ReKey(key, nonce)
> 	s.key = key[:len(s.key)]
> 	s.nonce = nonce[:len(s.nonce)]
> }
> 
https://github.com/ArteMisc/libgodium/blame/master/stream/chacha20.go#L74

Should that be s.Cipher.Rekey?

Poly is not initialized here:

https://github.com/ArteMisc/libgodium/blob/master/secretstream/xchacha20poly1305.go#L179

**Comment by ArteMisc** [comment]
`s.Rekey` should indeed be `s.Cipher.Rekey`, that is a bug.

I will have to look into the initialization issue with Poly.

Thanks for reporting these :)
